#!/bin/bash

curl icanhazip.com > /tmp/iptoday.txt


iptoday=/tmp/iptoday.txt
iptmp=/tmp/ip.txt

shatoday=$( sha256sum "$iptoday" | awk '{print $1}')
shatmp=$( sha256sum "$iptmp" | awk '{print $1}')


# Compare the checksums
if [ "x$shatoday" = "x$shatmp" ]
then
	printf "Files %s and %s are the same\n" "$shatoday" "$shatmp"
	exit 0
else
	printf "Files %s and %s are different\n" "$shatoday" "$shatmp"
	cat $iptoday |mail -s "change ip karatube" flottin@gmail.com
	mv $iptoday  $ip
    exit 1
fi

