#!/bin/bash

RED='\033[0;31m'
NC='\033[0m' # No Color

if [ -z "$1" ]; then 
    echo "usage killer [NAME]"
    exit
fi

function killpid {
    sudo kill -9 ${1} && echo "PID ${1} killed !" || echo "PID ${1} killed !"
}


ps -x | grep $1 |grep -v grep |grep -v killer
pidcount=$(ps -x | grep $1 |grep -v grep  |grep -v killer | awk '{print $1}' | wc -c )
pidnum=$(ps -x | grep $1 |grep -v grep |grep -v killer | awk '{print $1}' )
if [ -z "$pidnum" ] ; then
    echo "No pid found !"
    exit;
fi


if [ $pidcount -gt '7' ]; then

    printf "There are several PID ! "
    printf "Enter the PID to kill, type [n] or [q] to quit or [a] to killall ! "
    read killer
    if [ $killer = n ] || [ $killer = q ]; then
        echo "You aborted !"
        exit
    fi
    
    if [ $killer = a ] ; then
        killpid "$pidnum"
        exit;
    
    fi
    
    killpid ${killer}
    echo "It remains following PID ! Type [y] to show them, [n] or [q] to quit ! "
    read killer
    if [ $killer = n ] || [ $killer = q ]; then
        echo "You aborted !"
        exit
    fi
    
    if [ $killer = y ] ; then
          ps -x | grep $1 |grep -v grep |grep -v killer
        exit;
    fi
else
    printf "Kill ${RED}$pidnum${NC} by pressing [y] or [n] or [q] to quit ! \n"
    read killer
    if [ $killer = y ] ; then 
        killpid ${pidnum}
        exit;
    
    fi
    if [[ $key = n ]]; then
        echo " was pressed ! Aborted !"
       exit
    fi

    if [[ $key = q ]]; then
        echo " was pressed ! Aborted !"
       exit
    fi
    
fi

exit;
