#!/bin/bash

RED='\033[0;31m'
NC='\033[0m' # No Color
sep="\n${RED}-------------------------------------------------------------------------${NC}\n"
function alert {
    printf $sep
    printf "${RED}$1${NC}";
    printf $sep
}


if [ -z "$1" ]; then 
    alert "usage killer [NAME]"
    exit
fi

function killpid {
    sudo kill -9 ${1} && echo "PID ${1} killed !" || echo "PID ${1} killed !"
}

ps -x | grep $1 |grep -v grep |grep -v killer
pidcount=$(ps -x | grep $1 |grep -v grep  |grep -v killer | awk '{print $1}' | wc -c )
pidnum=$(ps -x | grep $1 |grep -v grep |grep -v killer | awk '{print $1}' )
if [ -z "$pidnum" ] ; then
    alert "No pid found !"
    exit;
fi


if [ $pidcount -gt '7' ]; then
    alert "Several PIDs' ! Enter PID to kill, [n] or [q] to quit, [a] to killall ! "
    read killer
    if [ $killer = n ] || [ $killer = q ]; then
        alert "You aborted !"
        exit
    fi
    
    if [ $killer = a ] ; then
        killpid "$pidnum"
        exit;
    
    fi
    
    killpid ${killer}
    alert "Remains following PID ! [y] to show them, [n] or [q] to quit ! "
    read killer
    if [ $killer = n ] || [ $killer = q ]; then
        alert "You aborted !"
        exit
    fi
    
    if [ $killer = y ] ; then
          ps -x | grep $1 |grep -v grep |grep -v killer
        exit;
    fi
else
    alert "Kill ${RED}$pidnum${NC} with [y], quit with [n] or [q]  ! \n"
    read killer
    if [ $killer = y ] ; then 
        killpid ${pidnum}
        exit;
    
    fi
    if [[ $key = n ]]; then
        alert " was pressed ! Aborted !"
       exit
    fi

    if [[ $key = q ]]; then
        alert " was pressed ! Aborted !"
       exit
    fi
    
fi

exit;
