#!/bin/bash
RED='\033[0;31m'
NC='\033[0m' # No Color
sep="\n${RED}-------------------------------------------------------------------------${NC}\n"


function alert {
    printf $sep
    printf "${RED}$1${NC}";
    printf $sep
}
path=$(realpath KillerApp/.)

# manage rights for first 
chmod -R 777 KillerApp && perms=777 || perms=false

if [ $perms = '777' ]; then
    alert "Good perms on KillerApp !"
else
    alert "chmod 777 killerApp ? Type [y] if ok, [n] or [q] to quit ! "
    read killer
    if [ $killer = n ] || [ $killer = q ]; then
        echo "You aborted !"
        exit
    fi
    if [ $killer = y ] ; then
        sudo chmod  -R 777 $path
    fi
fi

# test 2O process
alert "Test with  20 processes"
for i in {1..20}
do 
$path/dummyKiller & 
done
alert $path/'killer dummy'
$path/killer dummy
#~ alert $info
alert "Now let's test with one dummy process ? Type [y] if ok, [n] or [q] to quit ! "
read killer
if [ $killer = n ] || [ $killer = q ]; then
    echo "You aborted !"
    exit
fi

# test 1 process
if [ $killer = y ] ; then
    for i in {1..1}
        do 
        $path/dummyKiller & 
        done

        alert $path/'killer dummy'
        $path/killer dummy
fi

#without any process
alert "And then without any dummy ? Type [y] if ok, [n] or [q] to quit ! "
read killer
if [ $killer = n ] || [ $killer = q ]; then
    alert "You aborted !"
    exit
fi

if [ $killer = y ] ; then
    alert $path/'killer dummy'
    $path/killer dummy
fi


